name: build-and-lint

# triggers: define when this workflow should run
# triggers on push to these branches 
on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]


# Define a job( you can have multiple jobs here that will run )
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 22

        - name: Install backend dependencies
          working-directory: server
          run: npm ci

        - name: Lint backend
          working-directory: server
          run: npm run lint -- --max-warnings=0

        - name: Install frontend dependencies
          working-directory: client
          run: npm ci

        - name: Lint frontend
          working-directory: client
          run: npm run lint -- --max-warnings=0

        - name: Build backend Docker image
          run: docker build -t backend ./server

        - name: Build frontend Docker image
          run: docker build -t frontend ./client